modLoader = "javafml"
loaderVersion = "${forge_version_range}"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
	modId = "${mod_id}"
	version = "${version}"
	displayName = "${mod_name}"
	updateJSONURL = "${update}"
	displayURL = "${homepage}"
	logoFile = "${icon}"
	credits = "${credits}"
	authors = "${authors}"
	description = '''${description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#	config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "forge"
	mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
	mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
	modId = "architectury"
	mandatory = true
	versionRange = "${architectury_version_range}"
	ordering = "AFTER"
	side = "BOTH"
